services:
  - type: web
    name: foodorder
    env: node
    buildCommand: npm install && cd client && npm install && cd .. && npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
    disk:
      name: orders-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

